spring:
  application:
    name: y-ai-code-zgen
server:
  port: 8180
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: cn.y.yaicodezgen.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

